# Generated by Django 3.0.1 on 2019-12-27 14:16

from django.db import migrations, models
import website.models.blog_post


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField(blank=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('media_directory', models.CharField(default=website.models.blog_post.BlogPost.default_media_directory, editable=False, max_length=35)),
                ('preview_image', models.ImageField(blank=True, upload_to=website.models.blog_post.BlogPost.default_preview_image)),
            ],
        ),
    ]
