# Generated by Django 2.2.5 on 2019-10-27 08:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191027_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.ImageField(null=True, upload_to=main.models.get_upload_path),
        ),
    ]
